### ISSUE TITLE
Sign problem in Translation

### ISSUE THREAD

**Issue by Manueljohnson063** [Gltina/ACP-3Detection#5]
[0, 0, 1, 7],
[1, 0, 0, 0],
[0, 1, 0, -1.425],
[0, 0, 0, 1]]))
you are translating your points from 0.305----->1.73 then why you put -1.425 instead of +1.425 ?
Please help madam,thanks in advance

**Comment by leihui6** [comment]
@Manueljohnson063 This matrix is used in _tools/converter_data/fine_detection/converter_pc2KITTIpc.py_, but also in _tools/converter_data/rough_detection/converter_pc2KITTIpc.py_. In these script codes, we translated the point cloud by a minus value instead of a positive one, because the origin of the KITTI coordinate is up to the real objects.

**Comment by Manueljohnson063** [comment]
Dear Glitina,
Many many thanks for your replay.
